name: GitHub Actions RSS

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  rss-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py
      - name: Push Generated File
        run: |
          git config user.name auto-push
          git config user.email auto-push@example.com
          git add .
          git commit -m "auto push from ci" || echo no commits
          git push
